/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HtmlIndexRouteImport } from './routes/html/index'
import { Route as HtmlTestingIndexRouteImport } from './routes/html/testing/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlIndexRoute = HtmlIndexRouteImport.update({
  id: '/html/',
  path: '/html/',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlTestingIndexRoute = HtmlTestingIndexRouteImport.update({
  id: '/html/testing/',
  path: '/html/testing/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/html': typeof HtmlIndexRoute
  '/html/testing': typeof HtmlTestingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/html': typeof HtmlIndexRoute
  '/html/testing': typeof HtmlTestingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/html/': typeof HtmlIndexRoute
  '/html/testing/': typeof HtmlTestingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/html' | '/html/testing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/html' | '/html/testing'
  id: '__root__' | '/' | '/html/' | '/html/testing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HtmlIndexRoute: typeof HtmlIndexRoute
  HtmlTestingIndexRoute: typeof HtmlTestingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html/': {
      id: '/html/'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html/testing/': {
      id: '/html/testing/'
      path: '/html/testing'
      fullPath: '/html/testing'
      preLoaderRoute: typeof HtmlTestingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HtmlIndexRoute: HtmlIndexRoute,
  HtmlTestingIndexRoute: HtmlTestingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
